//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWithSwagger.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Actions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Actions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcWithSwagger.Localization.Actions", typeof(Actions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddUser-&gt;Description.
        /// </summary>
        internal static string AddUser_Description {
            get {
                return ResourceManager.GetString("AddUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddUser-&gt;Title.
        /// </summary>
        internal static string AddUser_Title {
            get {
                return ResourceManager.GetString("AddUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUser-&gt;Description.
        /// </summary>
        internal static string GetUser_Description {
            get {
                return ResourceManager.GetString("GetUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUser-&gt;Title.
        /// </summary>
        internal static string GetUser_Title {
            get {
                return ResourceManager.GetString("GetUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListUsers-&gt;Description.
        /// </summary>
        internal static string ListUsers_Description {
            get {
                return ResourceManager.GetString("ListUsers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListUsers-&gt;Title.
        /// </summary>
        internal static string ListUsers_Title {
            get {
                return ResourceManager.GetString("ListUsers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveUser-&gt;Description.
        /// </summary>
        internal static string RemoveUser_Description {
            get {
                return ResourceManager.GetString("RemoveUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveUser-&gt;Title.
        /// </summary>
        internal static string RemoveUser_Title {
            get {
                return ResourceManager.GetString("RemoveUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateUser-&gt;Description.
        /// </summary>
        internal static string UpdateUser_Description {
            get {
                return ResourceManager.GetString("UpdateUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateUser-&gt;Title.
        /// </summary>
        internal static string UpdateUser_Title {
            get {
                return ResourceManager.GetString("UpdateUser_Title", resourceCulture);
            }
        }
    }
}
